project:
  type: website
  render: 
    - "*.Rmd"
    - "*.qmd"
    - "!practicals/PART_II-DADA2_ANF.Rmd"

website:
  title: "ANF metabarcoding"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

