---
title: "About"
---

## Organisation committee and intervenants {.unnumbered}

Nicolas Henry, ABIMS, Station Biologique de Roscoff

Erwan Corre, ABIMS, Station Biologique de Roscoff

Jean-Christophe Auguet, Marbec, Montpellier

Lois Maignien, BEEP, Université de Brest

Marc Garel, MIO, Marseille

Fabrice Armougom, MIO, Marseille

## Sponsors {.unnumbered}

Plateforme OMICS, MIO, Marseille

Société Française de Bio-Informatique

Institut Français de Bioinformatique

Thanks the French Institute of Bioinformatics – IFB CNRS UAR3601 – for providing life science data and tools, storage and computing resources.
Partenaires


## Stuff to include {.unnumbered}

En matière de prospectives scientifiques, le CNRS (INSU OA) et l’IRD ambitionnent de caractériser la biodiversité environnementale afin d’étudier l’impact du changement global sur les milieux et de l’anthropisation de la planète. Ces enjeux nécessitent l’acquisition de connaissances sur la biodiversité pour répondre aux grands défis planétaires (e.g. modéliser, anticiper, prévenir les catastrophes écologiques), aux objectifs de développement durable, et contribuer aux grandes transitions de la société dans un contexte de changement climatique.

Le metabarcoding est aujourd’hui une des approches incontournable dans la description des écosystèmes pour répondre à ces enjeux scientifiques; elle offre une caractérisation exhaustive de la diversité taxonomique (composition en espèces et abondances) d’un écosystème via le séquençage massif de marqueurs d’intérêts (e.g. ARN ribosomaux 16S, 18S, gène COX, …) et le post-traitement bio-informatique des données générées.

L’Action Nationale de Formation CNRS-INSU MetaBioDiv, portée par l’Institut Méditerranéen d’Océanologie (Armougom F., MIO) et la Délégation Régionale Côte d’Azur CNRS (DR20, Pierrette Finsac), propose à la communauté scientifique une formation sur la caractérisation de la biodiversité taxonomique d’écosystèmes (procaryotes et micro-eucaryotes) par le prisme du séquençage haut-débit Illumina (Miseq) et du traitement bio-informatique associé (outils R sous Rstudio).

## Libraries used in practicals {.unnumbered}
```{r}
renv::dependencies() |> 
    dplyr::pull(Package) |>
    unique() |>
    sort()
```
