---
title: "ANF MetaBioDiv"
---

## Third edition (September 2025) {.unnumbered}

Welcome to the third edition of the ANF Exploration de la Diversité Taxonomique des Ecosystèmes par Metabarcoding. The aim of this course is to teach you how to run microbial ecology analyses (mostly alpha and beta diversity) from metabarcoding raw sequencing data using R.

### Program {.unnumbered}

You can also find a pdf version of the program [here](courses/PROGRAMME_ANF_METABIODIV_2025.pdf){target="_blank"}

-   Monday 29<sup>th</sup>:
    -   09h00: Participants arrival and installation
    -   12h30: {{< fa utensils >}}
    -   14h00: Training introduction I
    -   14h15: Introduction and [R practical](practicals/rforbeginer.html) by Marc Garel + check technical issues
    -   16h00: {{< fa mug-hot >}}
    -   16h15: [R practical](practicals/rforbeginer.html) by Marc Garel + check technical issues
    -   18h00: Seminar "Introduction bonne pratique" - -- i.e dépôt github, FAIR principles by M. Garel
    -   19h30: {{< fa utensils >}} Ice breack, apéritif and diner
-   Tuesday 30<sup>th</sup>:
    -   08h30: [Introduction Metabarcoding](courses/introduction.pdf){target="_blank"} to metabarcoding by Loïs Maignien
    -   09h30: [Analysing metabarcoding data with dada2](courses/dada2.html){target="_blank"} by Charlotte Berthelier
    -   10h15: {{< fa mug-hot >}}
    -   10h30: [Preprocessing: dada2](practicals/preprocessing_dada2.html) by Charlotte Berthelier
    -   12h30: {{< fa utensils >}}
    -   14h00: [Introduction to phyloseq](courses/phyloseq.html){target="_blank"}
    -   15h00: [Preprocessing: dada2](practicals/preprocessing_dada2.Rmd) and [Preprocessing: phyloseq](practicals/preprocessing_phyloseq.html) by Charlotte Berthelier
    -   16h00: {{< fa mug-hot >}}
    -   16h15: [Preprocessing: dada2](practicals/preprocessing_dada2.Rmd) and [Preprocessing: phyloseq](practicals/preprocessing_phyloseq.html) by Charlotte Berthelier
    -   18h00: Mise en place des repos de données perso pour ceux qu'il le souhaite outemps libre
    -   19h30: {{< fa utensils >}}
-   Wednesday 1<sup>st</sup>:
    -   08h30: Course on [alpha diversity](courses/alpha_diversity.pdf){target="_blank"} 1/2 by Fabrice Armougom and Elsa Mendes
    -   10h15: {{< fa mug-hot >}}
    -   10h30: [Alpha diversity practical](practicals/alpha_diversity.html) by Fabrice Armougom and Elsa Mendes
    -   12h30: {{< fa utensils >}}
    -   14h00: Séminaire [metabarcoding worklows](courses/ampliseq_presentation_ANF.html) by Charlotte Berthelier
    -   15h00: [Ampliseq configuration workflow](practicals/ampliseq.html) by Charlotte Berthelier and Marc Garel
    -   16h00: {{< fa mug-hot >}}
    -   16h15: [Ampliseq configuration workflow](practicals/ampliseq.html) by Charlotte Berthelier and Marc Garel
    -   17h15: Séminaire introduction Long Read by F. Armougom
    -   18h15: Mise en place des repos de données perso pour ceux qu'il le souhaite outemps libre
    -   19h30: {{< fa utensils >}}
-   Thursday 2<sup>nd</sup>:
    -   08h30: Course on [beta diversity](courses/beta_diversity.pdf){target="_blank"} 1/2 by Jean-Christophe Auguet
    -   10h15: {{< fa mug-hot >}}
    -   10h30: [Beta diversity practical](practicals/beta_diversity.html) by Jean-Christophe Auguet
    -   12h30: {{< fa utensils >}}
    -   14h00: Course on [beta diversity](courses/beta_diversity.pdf){target="_blank"} 2/2 by Jean-Christophe Auguet
    -   15h00: [Beta diversity practical](practicals/beta_diversity.html) by Jean-Christophe Auguet
    -   16h00: {{< fa mug-hot >}}
    -   16h15: [Beta diversity practical](practicals/beta_diversity.html) by Jean-Christophe Auguet
    -   18h00: free time
    -   19h30: {{< fa champagne-glasses >}} {{< fa utensils >}}
-   Friday 3<sup>rd</sup>:
    -   09h00: À la carte with {{< fa mug-hot >}}
    -   12h30: {{< fa utensils >}}
    -   14h00: End of the course
